version: '3.8'
services:
  example-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE=''
      - MYSQL_USER=''
      - MYSQL_PASSWORD=''
    ports:
      - 3306:3306
  example-app:
    build: Dockerfile
    restart: on-failure
    depends_on:
      - example-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_NAME=
      - DATABASE_PORT=