version: '3.8'
services:
  example-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=example
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306
  example-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - example-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=example
      - DATABASE_PORT=3306