#spring:
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  thymeleaf:#    cache: false
#  datasource:
#      url: jdbc:mysql://127.0.0.1:3306/venta?zeroDateTimeBehavior=convertToNull
#      username: root
#      password: admin#
#
#server:
#  port: 8080
#  servlet:
#    context-path: '/productos'
#---
