spring:
  profiles:
    active: development
  jackson:
    serialization:
      write-dates-as-timestamps: false
 # h2:
 #   console:
  #    enabled: true
  #    path: /h2-console
  
  jpa:
    
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    jdbc-url: jdbc:mysql://localhost/base01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    initialization-mode: always
server:
  port: 8080
  servlet:
    context-path: '/api'