CREATE TABLE T_CLIENT (
    P_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    DOCUMENT INTEGER NOT NULL,
    PHONE INTEGER NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL
);
CREATE TABLE T_PRODUCT (
    P_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    VALUE INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL
);
CREATE TABLE T_TRANSACTION_PRODUCT (
   P_ID INT AUTO_INCREMENT PRIMARY KEY,
   VALUE INTEGER NOT NULL,
   P_ID_PRODUCT INT NOT NULL,
   QUANTITY INTEGER NOT NULL
);
CREATE TABLE T_TRANSACTION (
    P_ID INT AUTO_INCREMENT PRIMARY KEY,
    STATE_ORDER VARCHAR(255) NOT NULL,
    DATE_ORDER TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    P_ID_CLIENT INT NOT NULL,
    P_ID_SELLER INT NOT NULL,
    F_ID_TRANSACTION_PRODUCT INT NOT NULL,
    foreign key (F_ID_TRANSACTION_PRODUCT) references T_TRANSACTION_PRODUCT(P_ID)
);
CREATE TABLE T_SELLER (
    P_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    DOCUMENT INTEGER NOT NULL,
    PHONE INTEGER NOT NULL
);
